import React from 'react';
import { StatusIndicator, StateWrapper, cn } from './shared';
import { Play, Pause, Square, ExternalLink, Settings2, BarChart2, Timer, Activity } from 'lucide-react';

const mockStrategies = [
  { id: 'strat-001', name: 'MACD_Crossover_v2', type: 'Trend', status: 'Running', successRate: '68%', lastRun: '2 mins ago' },
  { id: 'strat-002', name: 'Bollinger_Mean_Rev', type: 'Reversion', status: 'Paused', successRate: '54%', lastRun: '1 hour ago' },
  { id: 'strat-003', name: 'VWAP_Breakout', type: 'Momentum', status: 'Error', successRate: '72%', lastRun: '15 mins ago' },
];

export function Strategies() {
  const [selectedId, setSelectedId] = React.useState('strat-001');
  const [showConfirm, setShowConfirm] = React.useState<'stop' | 'deploy' | null>(null);
  const [isBacktesting, setIsBacktesting] = React.useState(false);

  return (
    <div className="space-y-6">
      {showConfirm && (<div className="fixed inset-0 z-50 flex items-center justify-center bg-neutral-900/50 backdrop-blur-sm"><div className="w-full max-w-sm rounded border border-neutral-200 bg-white p-6 shadow-xl"><h3 className="text-sm font-bold uppercase tracking-wider text-neutral-800">Confirm {showConfirm === 'stop' ? 'Lifecycle Termination' : 'Production Deployment'}</h3><p className="mt-2 text-xs text-neutral-500 leading-relaxed">This action will {showConfirm === 'stop' ? 'immediately halt all execution threads' : 'deploy the strategy to the live Broker Hub'}.</p><div className="mt-6 flex justify-end gap-3"><button onClick={() => setShowConfirm(null)} className="px-4 py-2 text-[10px] font-bold uppercase text-neutral-400 hover:text-neutral-600">Abort</button><button onClick={() => setShowConfirm(null)} className="rounded bg-neutral-900 px-4 py-2 text-[10px] font-bold uppercase text-white hover:bg-neutral-800">Confirm Action</button></div></div></div>)}
      <header className="flex items-center justify-between border-b border-neutral-200 pb-4"><div><h1 className="text-xl font-semibold text-neutral-800">Strategy Hub</h1><p className="text-sm text-neutral-500">Execution lifecycle and async job supervision</p></div><button onClick={() => setShowConfirm('deploy')} className="h-9 rounded bg-neutral-900 px-4 text-[10px] font-bold uppercase tracking-wider text-white hover:bg-neutral-800">Deploy New Instance</button></header>
      <div className="grid grid-cols-1 gap-6 xl:grid-cols-12">
        <div className="xl:col-span-4 space-y-3">
          <h2 className="text-xs font-bold uppercase tracking-wider text-neutral-400">Strategy Inventory</h2>
          <div className="rounded border border-neutral-200 bg-white overflow-hidden"><div className="divide-y divide-neutral-100">{mockStrategies.map((strat) => <div key={strat.id} className={cn("flex cursor-pointer items-center justify-between p-4 transition-colors hover:bg-neutral-50", selectedId === strat.id && "bg-neutral-50/50 border-r-2 border-r-neutral-800")} onClick={() => setSelectedId(strat.id)}><div className="min-w-0"><div className="text-xs font-bold text-neutral-800 truncate">{strat.name}</div><div className="text-[9px] font-mono text-neutral-400 uppercase tracking-tighter">{strat.id}</div></div><div className="flex flex-col items-end gap-1 shrink-0"><span className={cn("rounded px-1.5 py-0.5 text-[9px] font-bold uppercase", strat.status === 'Running' ? 'bg-emerald-100 text-emerald-700' : strat.status === 'Error' ? 'bg-rose-100 text-rose-700 border border-rose-200' : 'bg-amber-100 text-amber-700 border border-amber-200')}>{strat.status}</span><span className="text-[10px] font-mono text-neutral-400">{strat.successRate} WR</span></div></div>)}</div></div>
        </div>
        <div className="xl:col-span-8 space-y-6">
          <div className="rounded border border-neutral-200 bg-white p-6"><div className="mb-8 flex items-center justify-between border-b border-neutral-50 pb-6"><div><h3 className="text-lg font-semibold text-neutral-800">{mockStrategies.find(s => s.id === selectedId)?.name}</h3><div className="flex gap-4 mt-1"><div className="flex items-center gap-1.5 text-[10px] font-mono text-neutral-400 uppercase"><Timer className="h-3 w-3" /> Uptime: 4d 12h 04m</div><div className="flex items-center gap-1.5 text-[10px] font-mono text-neutral-400 uppercase"><Activity className="h-3 w-3" /> Trades: 1,402</div></div></div><div className="flex gap-2"><button onClick={() => setShowConfirm('stop')} title="Terminate Strategy" className="flex items-center gap-2 rounded border border-neutral-200 bg-white px-3 py-1.5 text-[10px] font-bold uppercase text-neutral-600 hover:bg-neutral-50"><Square className="h-3 w-3 fill-neutral-400 text-neutral-400" /> Stop Instance</button><div className="mx-1 w-px bg-neutral-100" /><button title="Configuration" className="p-2 rounded hover:bg-neutral-100 text-neutral-400"><Settings2 className="h-4 w-4" /></button></div></div><div className="grid grid-cols-1 gap-8 md:grid-cols-2"><div className="space-y-4"><h4 className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Risk Metrics (Read-Only)</h4><div className="grid grid-cols-2 gap-3">{[{ label: 'Sharpe', val: '1.84' }, { label: 'Max DD', val: '12.4%' }, { label: 'Avg PnL', val: '+$245' }, { label: 'Exposure', val: '$14.2k' }].map(m => (<div key={m.label} className="rounded border border-neutral-100 bg-neutral-50/30 p-3"><div className="text-[9px] font-bold text-neutral-400 uppercase tracking-tighter">{m.label}</div><div className={cn("text-sm font-mono font-bold", m.label === 'Avg PnL' ? 'text-emerald-600' : m.label === 'Max DD' ? 'text-rose-600' : 'text-neutral-700')}>{m.val}</div></div>))}</div></div><div className="space-y-4"><h4 className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Backtest Engine</h4><div className="rounded border border-neutral-200 bg-neutral-50 p-6 flex flex-col items-center justify-center min-h-[160px]">{isBacktesting ? (<div className="w-full space-y-4"><div className="flex justify-between items-center text-[10px] font-bold text-neutral-500 uppercase"><span>Simulating...</span><span className="animate-pulse">Processing...</span></div><div className="h-1.5 w-full bg-neutral-200 rounded-full overflow-hidden"><div className="h-full bg-neutral-800 animate-[progress_3s_ease-in-out_infinite]" style={{ width: '65%' }}></div></div></div>) : (<><BarChart2 className="mb-3 h-8 w-8 text-neutral-200" /><button onClick={() => { setIsBacktesting(true); setTimeout(() => setIsBacktesting(false), 5000); }} className="mt-4 rounded bg-white border border-neutral-200 px-4 py-2 text-[10px] font-bold uppercase text-neutral-600 hover:bg-neutral-50">Run New Simulation</button></>)}</div></div></div></div>
          <div className="space-y-3"><h2 className="text-xs font-bold uppercase tracking-wider text-neutral-400">Execution Stream</h2><div className="rounded border border-neutral-200 bg-neutral-900 p-4 font-mono text-[9px] leading-relaxed text-neutral-400"><div className="flex gap-2"><span className="text-neutral-600 shrink-0">14:20:01</span><span className="text-neutral-500 uppercase shrink-0 font-bold">[INFO]</span><span>STRATEGY_INIT_SEQUENCE_START [Instance: {selectedId}]</span></div></div></div>
        </div>
      </div>
    </div>
  );
}
